version: "3"

tasks:
  # Default task to list all available tasks
  default:
    desc: "List all available tasks"
    cmds:
      - task: list

  build:
    desc: "Produce a bootable Helix installer ISO"
    cmds:
      - sudo nix run --impure --accept-flake-config --no-write-lock-file --print-build-logs 'path:.#helix-os-base' -- --output ./artifacts

  test:
    desc: "Sanity check the Helix installer ISO contents"
    cmds:
      - ./scripts/test-installer.sh

  run-installer:
    desc: "Boot the latest Helix installer ISO with QEMU"
    cmds:
      - ./scripts/run-installer.sh

  clean:
    desc: "Clean up old build artifacts"
    cmds:
      - sudo rm -rf artifacts result result-*
      - nix store gc
